---
ID: "202a341f-8d2f-43bd-89b7-319f27a04713"
Parent: "3c4eae73-7e7f-4648-a863-bd250d76ccf8"
Template: "3c4eae73-7e7f-4648-a863-bd250d76ccf8"
Path: "/sitecore/templates/Project/industry-verticals/Custom Templates/Article/Categories/Category/__Standard Values"
SharedFields:
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "d5c4e1a1-f2a4-4eca-a3ff-39e58b6015b5"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 1
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260115T130822Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "15205d76-82ac-4188-b19d-c78eab27c42c"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260213T062820Z
    - ID: "f9fd853f-2691-40b4-81d1-00ccf1a6cc06"
      Hint: Category
      Value: $name
